### ISSUE TITLE
Add the ability to customize the permissions granted to the Cloud Build service account

### ISSUE THREAD

**Issue by robmorgan** [gruntwork-io/terraform-google-ci#7]
Cloud Build executes builds with the permissions granted to the Cloud Build service account tied to the project. You can grant additional roles to the service account to allow Cloud Build to interact with other GCP services. We should look at providing a way to facilitate this whether that be through an option or the implementation of a dedicated module.

**Comment by MoonMoon1919** [comment]
Closing this issue since this repo has been in "sunsetting" for 12 months.
